name: language_picker_example
description: Example application of language_picker Flutter package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.3.3

dependencies:
  flutter:
    sdk: flutter

  language_picker_native_tongue:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
